//! Generate operation/right tables from `spec/heap/operations-v1.json`.

use serde::Deserialize;
use std::env;
use std::fs;
use std::path::PathBuf;

#[derive(Deserialize)]
struct OpsDoc {
    rights: Vec<RightEntry>,
    operations: Vec<OpEntry>,
    state_admission: serde_json::Map<String, serde_json::Value>,
}

#[derive(Deserialize)]
struct RightEntry {
    name: String,
    bit: u8,
    mask: u64,
}

#[derive(Deserialize)]
struct OpEntry {
    id: u16,
    wire_name: String,
    status: String,
    rights_mask: u64,
    allowed_states: Vec<String>,
    returns_data: bool,
    mutates_data: bool,
}

fn main() {
    // Allow `#[cfg(kani)]` harnesses without unexpected_cfgs warnings under cargo test.
    println!("cargo::rustc-check-cfg=cfg(kani)");
    println!("cargo:rustc-check-cfg=cfg(kani)");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    // Prefer crate-local copies (crates.io packages cannot reach monorepo `spec/heap/`).
    // Fall back to workspace root for in-tree developer builds.
    let resolve_spec = |name: &str| -> PathBuf {
        let local = manifest_dir.join("spec").join(name);
        if local.is_file() {
            return local;
        }
        let workspace_root = manifest_dir
            .parent()
            .and_then(|p| p.parent())
            .expect("workspace root")
            .to_path_buf();
        workspace_root.join("spec/heap").join(name)
    };
    let ops_path = resolve_spec("operations-v1.json");
    let cbor_path = resolve_spec("cbor-v1.json");
    let vectors_path = resolve_spec("vectors-v1.json");
    let isolation_path = resolve_spec("isolation-profiles-v1.json");

    println!("cargo:rerun-if-changed={}", ops_path.display());
    println!("cargo:rerun-if-changed={}", cbor_path.display());
    println!("cargo:rerun-if-changed={}", vectors_path.display());
    println!("cargo:rerun-if-changed={}", isolation_path.display());

    let ops: OpsDoc =
        serde_json::from_str(&fs::read_to_string(&ops_path).expect("operations-v1.json"))
            .expect("parse operations-v1.json");

    // Uniqueness
    let mut ids = std::collections::BTreeSet::new();
    let mut names = std::collections::BTreeSet::new();
    for op in &ops.operations {
        assert!(ids.insert(op.id), "duplicate operation id {}", op.id);
        assert!(
            names.insert(op.wire_name.clone()),
            "duplicate wire name {}",
            op.wire_name
        );
    }
    let active: Vec<_> = ops
        .operations
        .iter()
        .filter(|o| o.status == "active")
        .map(|o| o.id)
        .collect();
    // HP-000 baseline: 1–3 always active. Later packages may activate more via §32.4.
    for required in [1u16, 2, 3] {
        assert!(
            active.contains(&required),
            "active set must include process op {required}, got {active:?}"
        );
    }
    assert!(
        active.windows(2).all(|w| w[0] < w[1]),
        "active operation ids must be sorted unique: {active:?}"
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let mut gen = String::new();
    gen.push_str("// @generated by residiuum-heap/build.rs — do not edit.\n");
    gen.push_str("/// Right bit definitions from `spec/heap/operations-v1.json`.\n");
    gen.push_str("#[allow(non_snake_case, dead_code)]\n");
    gen.push_str("pub mod generated_rights {\n");
    for r in &ops.rights {
        gen.push_str(&format!(
            "    /// {} right bit {}.\n    pub const {}: u64 = 0x{:016x};\n",
            r.name,
            r.bit,
            r.name.to_uppercase(),
            r.mask,
        ));
    }
    gen.push_str("}\n\n");

    gen.push_str("/// Operation registry rows from `spec/heap/operations-v1.json`.\n");
    gen.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    gen.push_str("pub struct GeneratedOp {\n");
    gen.push_str("    pub id: u16,\n");
    gen.push_str("    pub wire_name: &'static str,\n");
    gen.push_str("    pub status: &'static str,\n");
    gen.push_str("    pub rights_mask: u64,\n");
    gen.push_str("    pub returns_data: bool,\n");
    gen.push_str("    pub mutates_data: bool,\n");
    gen.push_str("}\n\n");
    gen.push_str("pub static GENERATED_OPS: &[GeneratedOp] = &[\n");
    for op in &ops.operations {
        gen.push_str(&format!(
            "    GeneratedOp {{ id: {}, wire_name: \"{}\", status: \"{}\", rights_mask: 0x{:x}, returns_data: {}, mutates_data: {} }},\n",
            op.id, op.wire_name, op.status, op.rights_mask, op.returns_data, op.mutates_data
        ));
    }
    gen.push_str("];\n\n");

    gen.push_str("pub fn generated_op(id: u16) -> Option<&'static GeneratedOp> {\n");
    gen.push_str("    GENERATED_OPS.iter().find(|o| o.id == id)\n");
    gen.push_str("}\n\n");

    gen.push_str("pub fn active_operation_ids() -> &'static [u16] {\n");
    let active_lit = active
        .iter()
        .map(|i| i.to_string())
        .collect::<Vec<_>>()
        .join(", ");
    gen.push_str(&format!("    &[{active_lit}]\n"));
    gen.push_str("}\n");

    // State admission table
    gen.push_str("\n/// Administrative-state admission: state name -> admitted op IDs.\n");
    gen.push_str("pub fn admitted_ops_for_state(state: &str) -> Option<&'static [u16]> {\n");
    gen.push_str("    match state {\n");
    for (state, ids_val) in &ops.state_admission {
        let ids: Vec<u16> = serde_json::from_value(ids_val.clone()).expect("state ids");
        let lit = ids
            .iter()
            .map(|i| i.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        gen.push_str(&format!("        \"{state}\" => Some(&[{lit}]),\n"));
    }
    gen.push_str("        _ => None,\n");
    gen.push_str("    }\n");
    gen.push_str("}\n");

    // Capture allowed_states per op for tests
    gen.push_str("\npub fn allowed_states_for_op(id: u16) -> Option<&'static [&'static str]> {\n");
    gen.push_str("    match id {\n");
    for op in &ops.operations {
        if op.allowed_states.is_empty() {
            gen.push_str(&format!("        {} => Some(&[]),\n", op.id));
        } else {
            let lit = op
                .allowed_states
                .iter()
                .map(|s| format!("\"{s}\""))
                .collect::<Vec<_>>()
                .join(", ");
            gen.push_str(&format!("        {} => Some(&[{lit}]),\n", op.id));
        }
    }
    gen.push_str("        _ => None,\n");
    gen.push_str("    }\n");
    gen.push_str("}\n");

    fs::write(out_dir.join("generated_registry.rs"), gen).expect("write generated_registry.rs");

    // Copy artifact digests into env for drift checks
    for (label, path) in [
        ("OPS", &ops_path),
        ("CBOR", &cbor_path),
        ("VECTORS", &vectors_path),
    ] {
        let bytes = fs::read(path).unwrap();
        let digest = {
            use std::collections::hash_map::DefaultHasher;
            use std::hash::{Hash, Hasher};
            let mut h = DefaultHasher::new();
            bytes.hash(&mut h);
            h.finish()
        };
        println!("cargo:rustc-env=HEAP_{label}_LEN={}", bytes.len());
        println!("cargo:rustc-env=HEAP_{label}_HASH={digest}");
    }
}
