//! Residiuum three-prong store stress / integrity rig (not a product CLI).
//!
//! 1. **pump** — autogenerated puts until on-disk size ≥ target (default 1 GiB)
//! 2. **chaos** — offline random garbage writes into `.residiuum` segment files
//! 3. **monitor** — latency + salvage/scrub diagnostics
//!
//! Orchestrator: **run** = pump → baseline monitor → chaos → post-chaos monitor.
//! Scale ladder: pass at 1 GiB, then 10 GiB, then larger.

mod ack_finalize;
mod chaos;
mod manifest;
mod monitor;
mod peer;
mod phase_bench;
mod pump;
mod size;
mod write_mimic;

use ack_finalize::{
    run_ack_finalize, run_ack_finalize_matrix, run_enrichment_off_control,
    run_seal_fast_lane_measure, run_seal_interference_control, run_zero_scan_auth_seal_measure,
    AckFinalizeConfig, MeasureCell,
};
use chaos::{run_chaos, ChaosConfig};
use clap::{Parser, Subcommand};
use manifest::{manifest_path_for_store, per_store_manifest_path, store_path_for, MAX_STORES};
use monitor::{evaluate_run, run_monitor, MonitorConfig};
use peer::{
    parse_awo_mode, parse_diag_io, parse_engine, parse_mode, parse_segment_growth, run_peer_pump,
    PeerConfig,
};
use phase_bench::{run_phase_bench, PhaseBenchConfig};
use pump::{ensure_parent, parse_durability, run_pump, PumpConfig};
use serde_json::{json, Value};
use size::{default_min_free_for_target, format_bytes, parse_size};
use std::path::PathBuf;
use std::process::ExitCode;
use std::time::{SystemTime, UNIX_EPOCH};
use write_mimic::{
    run_write_mimic, MimicMode, WriteMimicConfig, PEER_DATA_BYTES_PER_OP, PEER_INDEX_APPEND_BYTES,
    PEER_INDEX_CHECKPOINT_EVERY, PEER_INDEX_END_BYTES, PEER_OPS,
};

const ABOUT: &str = "Three-prong Residiuum store stress rig: pump · chaos · monitor";

#[derive(Parser)]
#[command(
    name = "residiuum-testrig",
    about = ABOUT,
    long_about = "Non-product harness for scale + damage campaigns.\n\n\
        Prong 1 (pump): fill a store to a target on-disk size with synthetic keys.\n\
        Prong 2 (chaos): punch random garbage into segment files while closed.\n\
        Prong 3 (monitor): measure gets/puts, salvage holes, scrub findings.\n\n\
        Suggested ladder: --target-bytes 1G, then 10G, then larger.\n\
        Numbers are diagnostic only (see doc/reference/operations/BENCHMARK_DISCLOSURE.md)."
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Prong 1: pump autogenerated data until on-disk size ≥ target.
    Pump {
        /// Store directory (created if missing).
        #[arg(long, short = 's')]
        store: PathBuf,
        /// Target on-disk size (e.g. 1G, 10G, 256M). Default 1G.
        #[arg(long, default_value = "1G")]
        target_bytes: String,
        /// Synthetic payload size in bytes.
        #[arg(long, default_value_t = 4096)]
        payload_size: usize,
        /// Durability: memory | buffered | durable.
        #[arg(long, default_value = "buffered")]
        durability: String,
        /// Soft seal threshold for segment rotation.
        #[arg(long, default_value = "64M")]
        seal_threshold: String,
        /// RNG seed for payload fill (0 = from clock).
        #[arg(long, default_value_t = 0)]
        seed: u64,
        /// Key prefix (decimal index appended).
        #[arg(long, default_value = "load/")]
        key_prefix: String,
        /// Manifest path (default: sibling testrig-manifest.v1.json).
        #[arg(long)]
        manifest: Option<PathBuf>,
        /// Writer shards for multi-core append (DEF-096 Axis B). 1 = legacy single
        /// active segment; N>1 uses create_with_shards + put_many. Fixed at create.
        #[arg(long, default_value_t = 1)]
        writer_shards: usize,
        /// Independent store roots (DEF-096 Axis C). 1 = single process; N>1 spawns
        /// N child pumps under `<store>/store-00` … (multi-process capacity harness).
        #[arg(long, default_value_t = 1)]
        stores: usize,
        /// Minimum free space on the store volume before pumping. Default: auto
        /// (≈2.5× target + 512 MiB). Pass `0` to disable. Near-full disks contaminate rates.
        #[arg(long, default_value = "auto")]
        min_free: String,
        /// Puts per `put_many` flush. `0` = auto (128 single-shard). Use `1` to
        /// simulate general single-put load (one Buffered OS write per key).
        #[arg(long, default_value_t = 0)]
        put_batch_size: usize,
        /// Machine-readable JSON on stdout.
        #[arg(long)]
        json_out: bool,
    },
    /// Prong 2: write garbage at random offsets in segment files (store must be closed).
    Chaos {
        /// Store directory.
        #[arg(long, short = 's')]
        store: PathBuf,
        /// Number of random punches.
        #[arg(long, default_value_t = 16)]
        hits: u32,
        /// Bytes of garbage per punch.
        #[arg(long, default_value_t = 64)]
        bytes_per_hit: usize,
        /// RNG seed (0 = from clock).
        #[arg(long, default_value_t = 0)]
        seed: u64,
        /// Protect this many leading bytes of each file (unless --brutal).
        #[arg(long, default_value_t = 4096)]
        protect_head: u64,
        /// Protect this many trailing bytes (unless --brutal).
        #[arg(long, default_value_t = 64)]
        protect_tail: u64,
        /// Allow punching segment headers / tails.
        #[arg(long)]
        brutal: bool,
        #[arg(long)]
        json_out: bool,
    },
    /// Prong 3: performance + integrity sample.
    Monitor {
        /// Store directory.
        #[arg(long, short = 's')]
        store: PathBuf,
        /// Optional workload manifest from pump.
        #[arg(long)]
        manifest: Option<PathBuf>,
        /// How many keys to sample for get latency.
        #[arg(long, default_value_t = 64)]
        sample_keys: usize,
        /// Optional buffered put microbench count (0 = skip).
        #[arg(long, default_value_t = 32)]
        put_samples: usize,
        /// Label for this sample (baseline | post-chaos | …).
        #[arg(long, default_value = "adhoc")]
        phase: String,
        /// Skip writer-path scrub/puts (inspect + salvage only).
        #[arg(long)]
        inspect_only: bool,
        #[arg(long)]
        json_out: bool,
    },
    /// Full campaign: pump → baseline monitor → chaos → post-chaos monitor.
    Run {
        /// Work directory (store created as `<work>/store`).
        #[arg(long, short = 'w')]
        work: PathBuf,
        /// Target on-disk size (default 1G). Use 8M/32M for smoke.
        #[arg(long, default_value = "1G")]
        target_bytes: String,
        #[arg(long, default_value_t = 4096)]
        payload_size: usize,
        #[arg(long, default_value = "buffered")]
        durability: String,
        #[arg(long, default_value = "64M")]
        seal_threshold: String,
        #[arg(long, default_value_t = 16)]
        chaos_hits: u32,
        #[arg(long, default_value_t = 64)]
        chaos_bytes: usize,
        #[arg(long, default_value_t = 0)]
        seed: u64,
        #[arg(long, default_value_t = 64)]
        sample_keys: usize,
        /// Allow chaos into headers.
        #[arg(long)]
        brutal: bool,
        /// Writer shards for multi-core append (DEF-096 Axis B). 1 = single active
        /// segment; N>1 creates with N shards and pumps via put_many.
        #[arg(long, default_value_t = 1)]
        writer_shards: usize,
        /// Independent store roots (DEF-096 Axis C). 1 = `<work>/store`; N>1 spawns
        /// N child pumps at `<work>/store-00` … (multi-process capacity harness).
        #[arg(long, default_value_t = 1)]
        stores: usize,
        /// Minimum free space on the work volume before pumping. Default: auto
        /// (≈2.5× target + 512 MiB). Pass `0` to disable.
        #[arg(long, default_value = "auto")]
        min_free: String,
        #[arg(long)]
        json_out: bool,
    },
    /// Diagnostic: phase breakdown (Blake vs raw write vs Memory vs Buffered put).
    ///
    /// Falsifies "CPU/Blake bound" when process CPU stays low: pure Blake should
    /// be huge ops/s; large Memory→Buffered gap means blocking OS write wait.
    PhaseBench {
        /// Work directory (stores created under it; deleted after each phase).
        #[arg(long, short = 'w')]
        work: PathBuf,
        /// Number of operations per phase (keep modest on external SSDs).
        #[arg(long, default_value_t = 20_000)]
        ops: u64,
        #[arg(long, default_value_t = 8192)]
        payload_size: usize,
        /// Batch size for put_many phase.
        #[arg(long, default_value_t = 128)]
        batch: usize,
        #[arg(long)]
        json_out: bool,
    },
    /// PEER-SQL same-bed peer pump: Residiuum or SQLite under mode A/B.
    ///
    /// Target is **logical payload** (`keys * payload_size`). Compare A vs A and
    /// B vs B only. See doc/wip/status/surveys/README-PEER-SQL.md.
    PeerPump {
        /// Work directory (Residiuum: `work/store`; SQLite: `work/peer.sqlite`).
        #[arg(long, short = 'w')]
        work: PathBuf,
        /// Engine: residiuum | sqlite
        #[arg(long)]
        engine: String,
        /// Mode: A (autocommit / batch=1) | B (txn-128 / batch=128)
        #[arg(long)]
        mode: String,
        /// Logical payload budget (default 256M).
        #[arg(long, default_value = "256M")]
        target_bytes: String,
        #[arg(long, default_value_t = 8192)]
        payload_size: usize,
        #[arg(long, default_value_t = 0)]
        seed: u64,
        /// Minimum free space (auto ≈2.5× target + 512 MiB). Pass `0` to disable.
        #[arg(long, default_value = "auto")]
        min_free: String,
        /// Soft seal threshold (e.g. 64M, 512M). Default 64M.
        #[arg(long, default_value = "64M")]
        seal_threshold: String,
        /// Residiuum AWO: disabled | static | adaptive (ignored for sqlite).
        #[arg(long, default_value = "disabled")]
        awo_mode: String,
        /// Concurrent client threads (server-async feed). Default 1 = embedded sync.
        #[arg(long, default_value_t = 1)]
        concurrency: usize,
        /// Residiuum diagnostic segment-tail I/O:
        /// real | discard | devnull | coalesce100k | seekonly | realnoseek |
        /// realoverwrite | realprealloc | realpreallocfill |
        /// realpreallocfcntl | realprealloczero | realpreallocwm.
        /// coalesce100k requires --concurrency > 1 (250 ms floor hangs QD=1).
        /// Aliases: coalesce, coalesce64k, 100k, 64k → coalesce100k (≥100 KiB or 250 ms).
        #[arg(long, default_value = "real")]
        diag_io: String,
        /// Residiuum product segment growth: grow (default) | watermark.
        /// Watermark = OS preallocate + ahead-of-write zero (opt-in; not default-on).
        /// Default capacity/chunk are 64 MiB; override with --wm-capacity-mib / --wm-chunk-mib.
        #[arg(long, default_value = "grow")]
        segment_growth: String,
        /// Watermark reserved capacity in MiB (requires --segment-growth watermark).
        /// Default 64. Use larger values (e.g. 10240) for multi‑GiB extend steps.
        #[arg(long)]
        wm_capacity_mib: Option<u64>,
        /// Watermark zero-runway chunk in MiB (requires --segment-growth watermark).
        /// Default 64.
        #[arg(long)]
        wm_chunk_mib: Option<u64>,
        /// Residiuum diagnostic: skip dual-index publish / derived checkpoints
        /// (isolates data cook+append+write from index).
        #[arg(long, default_value_t = false)]
        diag_skip_index: bool,
        /// Residiuum diagnostic: enable boundary probe and report data-write vs
        /// index (publish/post) timing sums in JSON.
        #[arg(long, default_value_t = false)]
        boundary_probe: bool,
        #[arg(long)]
        json_out: bool,
    },
    /// Ack/finalisation split (NEXT_MEASUREMENT.md). Measurement only.
    ///
    /// Emits acknowledged_write_ops_per_sec vs lifecycle_ops_per_sec.
    /// Fail-closed on seal_active and reopen ledger check. AWO always disabled.
    AckFinalize {
        /// Work directory (ephemeral; cleaned by --matrix after evidence).
        #[arg(long, short = 'w')]
        work: PathBuf,
        /// Cell: real-full | skip-index | discard | raw-mimic
        #[arg(long)]
        cell: String,
        /// Logical payload budget (default 256M).
        #[arg(long, default_value = "256M")]
        target_bytes: String,
        #[arg(long, default_value_t = 8192)]
        payload_size: usize,
        #[arg(long, default_value_t = 8)]
        concurrency: usize,
        #[arg(long, default_value_t = 42)]
        seed: u64,
        #[arg(long, default_value = "64M")]
        seal_threshold: String,
        #[arg(long, default_value = "auto")]
        min_free: String,
        /// Disable Hydra/Chimera enqueue (causal isolation for seal gates).
        #[arg(long, default_value_t = false)]
        no_enrichment: bool,
        #[arg(long)]
        json_out: bool,
    },
    /// Run the four-cell NEXT_MEASUREMENT matrix; write evidence table.
    AckFinalizeMatrix {
        /// Parent work directory (per-cell subdirs created then removed).
        #[arg(long, short = 'w')]
        work: PathBuf,
        /// Directory for matrix.json + EVIDENCE_TABLE.md + per-cell JSON.
        #[arg(long)]
        evidence: PathBuf,
        #[arg(long, default_value = "256M")]
        target_bytes: String,
        #[arg(long, default_value_t = 8192)]
        payload_size: usize,
        #[arg(long, default_value_t = 8)]
        concurrency: usize,
        #[arg(long, default_value_t = 42)]
        seed: u64,
        #[arg(long, default_value = "64M")]
        seal_threshold: String,
        #[arg(long, default_value = "auto")]
        min_free: String,
    },
    /// Seal Fast Lane: Real Full @ 64M with multi-rotate; ack vs ~83K control.
    SealFastLane {
        #[arg(long, short = 'w')]
        work: PathBuf,
        #[arg(long)]
        evidence: PathBuf,
        #[arg(long, default_value = "256M")]
        target_bytes: String,
        #[arg(long, default_value_t = 8192)]
        payload_size: usize,
        #[arg(long, default_value_t = 8)]
        concurrency: usize,
        #[arg(long, default_value_t = 42)]
        seed: u64,
        #[arg(long, default_value = "auto")]
        min_free: String,
    },
    /// Enrichment-off control @ 64M: separates enrichment contention vs auth finalize.
    EnrichmentOffControl {
        #[arg(long, short = 'w')]
        work: PathBuf,
        #[arg(long)]
        evidence: PathBuf,
        #[arg(long, default_value = "256M")]
        target_bytes: String,
        #[arg(long, default_value_t = 8192)]
        payload_size: usize,
        #[arg(long, default_value_t = 8)]
        concurrency: usize,
        #[arg(long, default_value_t = 42)]
        seed: u64,
        #[arg(long, default_value = "auto")]
        min_free: String,
    },
    /// Zero-Scan Authoritative Seal: Real Full @ 64M; ack ≥ 74.7K with exact reopen.
    ZeroScanAuthSeal {
        #[arg(long, short = 'w')]
        work: PathBuf,
        #[arg(long)]
        evidence: PathBuf,
        #[arg(long, default_value = "256M")]
        target_bytes: String,
        #[arg(long, default_value_t = 8192)]
        payload_size: usize,
        #[arg(long, default_value_t = 8)]
        concurrency: usize,
        #[arg(long, default_value_t = 42)]
        seed: u64,
        #[arg(long, default_value = "auto")]
        min_free: String,
    },
    /// Seal Interference Control: Real Full at 64M / 512M / 1G seal thresholds.
    ///
    /// Records pending seals at last ack + seal stage breakdown. Measurement only.
    SealInterferenceControl {
        #[arg(long, short = 'w')]
        work: PathBuf,
        /// Evidence directory (archive outside active todo when required).
        #[arg(long)]
        evidence: PathBuf,
        #[arg(long, default_value = "256M")]
        target_bytes: String,
        #[arg(long, default_value_t = 8192)]
        payload_size: usize,
        #[arg(long, default_value_t = 8)]
        concurrency: usize,
        #[arg(long, default_value_t = 42)]
        seed: u64,
        #[arg(long, default_value = "auto")]
        min_free: String,
    },
    /// Experimental: mimic Residiuum peer disk write sizes (data + index shapes).
    ///
    /// Not product TPS. Defaults calibrated to Mode A peer (32 768 × ~8440 B data).
    WriteMimic {
        /// Work directory (ephemeral; caller should rm -rf after).
        #[arg(long, short = 'w')]
        work: PathBuf,
        /// Mode: data | atomic | append
        #[arg(long, default_value = "data")]
        mode: String,
        /// Number of put-shaped ops (default = peer 256 MiB / 8 KiB).
        #[arg(long, default_value_t = PEER_OPS)]
        ops: u64,
        /// Bytes per data `write_all` (default = skip-index measured mean).
        #[arg(long, default_value_t = PEER_DATA_BYTES_PER_OP)]
        data_bytes_per_op: usize,
        /// Bytes per index-append record / atomic growth step.
        #[arg(long, default_value_t = PEER_INDEX_APPEND_BYTES)]
        index_append_bytes: usize,
        /// Atomic index checkpoint every N ops (0 = never mid-run).
        #[arg(long, default_value_t = PEER_INDEX_CHECKPOINT_EVERY)]
        index_checkpoint_every: u64,
        /// Final atomic index rewrite size (atomic mode; peer full−skip delta).
        #[arg(long, default_value_t = PEER_INDEX_END_BYTES)]
        index_end_bytes: usize,
        #[arg(long)]
        json_out: bool,
    },
}

fn main() -> ExitCode {
    let cli = Cli::parse();
    let result = match cli.command {
        Command::Pump {
            store,
            target_bytes,
            payload_size,
            durability,
            seal_threshold,
            seed,
            key_prefix,
            manifest,
            writer_shards,
            stores,
            min_free,
            put_batch_size,
            json_out,
        } => cmd_pump(
            store,
            target_bytes,
            payload_size,
            durability,
            seal_threshold,
            seed,
            key_prefix,
            manifest,
            writer_shards,
            stores,
            min_free,
            put_batch_size,
            json_out,
        ),
        Command::Chaos {
            store,
            hits,
            bytes_per_hit,
            seed,
            protect_head,
            protect_tail,
            brutal,
            json_out,
        } => cmd_chaos(
            store,
            hits,
            bytes_per_hit,
            seed,
            protect_head,
            protect_tail,
            brutal,
            json_out,
        ),
        Command::Monitor {
            store,
            manifest,
            sample_keys,
            put_samples,
            phase,
            inspect_only,
            json_out,
        } => cmd_monitor(
            store,
            manifest,
            sample_keys,
            put_samples,
            phase,
            inspect_only,
            json_out,
        ),
        Command::Run {
            work,
            target_bytes,
            payload_size,
            durability,
            seal_threshold,
            chaos_hits,
            chaos_bytes,
            seed,
            sample_keys,
            brutal,
            writer_shards,
            stores,
            min_free,
            json_out,
        } => cmd_run(
            work,
            target_bytes,
            payload_size,
            durability,
            seal_threshold,
            chaos_hits,
            chaos_bytes,
            seed,
            sample_keys,
            brutal,
            writer_shards,
            stores,
            min_free,
            json_out,
        ),
        Command::PhaseBench {
            work,
            ops,
            payload_size,
            batch,
            json_out,
        } => run_phase_bench(&PhaseBenchConfig {
            work,
            ops,
            payload_size,
            batch,
            json_out,
        }),
        Command::PeerPump {
            work,
            engine,
            mode,
            target_bytes,
            payload_size,
            seed,
            min_free,
            seal_threshold,
            awo_mode,
            concurrency,
            diag_io,
            segment_growth,
            wm_capacity_mib,
            wm_chunk_mib,
            diag_skip_index,
            boundary_probe,
            json_out,
        } => cmd_peer_pump(
            work,
            engine,
            mode,
            target_bytes,
            payload_size,
            seed,
            min_free,
            seal_threshold,
            awo_mode,
            concurrency,
            diag_io,
            segment_growth,
            wm_capacity_mib,
            wm_chunk_mib,
            diag_skip_index,
            boundary_probe,
            json_out,
        ),
        Command::AckFinalize {
            work,
            cell,
            target_bytes,
            payload_size,
            concurrency,
            seed,
            seal_threshold,
            min_free,
            no_enrichment,
            json_out,
        } => cmd_ack_finalize(
            work,
            cell,
            target_bytes,
            payload_size,
            concurrency,
            seed,
            seal_threshold,
            min_free,
            !no_enrichment,
            json_out,
        ),
        Command::AckFinalizeMatrix {
            work,
            evidence,
            target_bytes,
            payload_size,
            concurrency,
            seed,
            seal_threshold,
            min_free,
        } => cmd_ack_finalize_matrix(
            work,
            evidence,
            target_bytes,
            payload_size,
            concurrency,
            seed,
            seal_threshold,
            min_free,
        ),
        Command::SealFastLane {
            work,
            evidence,
            target_bytes,
            payload_size,
            concurrency,
            seed,
            min_free,
        } => cmd_seal_fast_lane(
            work,
            evidence,
            target_bytes,
            payload_size,
            concurrency,
            seed,
            min_free,
        ),
        Command::EnrichmentOffControl {
            work,
            evidence,
            target_bytes,
            payload_size,
            concurrency,
            seed,
            min_free,
        } => cmd_enrichment_off_control(
            work,
            evidence,
            target_bytes,
            payload_size,
            concurrency,
            seed,
            min_free,
        ),
        Command::ZeroScanAuthSeal {
            work,
            evidence,
            target_bytes,
            payload_size,
            concurrency,
            seed,
            min_free,
        } => cmd_zero_scan_auth_seal(
            work,
            evidence,
            target_bytes,
            payload_size,
            concurrency,
            seed,
            min_free,
        ),
        Command::SealInterferenceControl {
            work,
            evidence,
            target_bytes,
            payload_size,
            concurrency,
            seed,
            min_free,
        } => cmd_seal_interference_control(
            work,
            evidence,
            target_bytes,
            payload_size,
            concurrency,
            seed,
            min_free,
        ),
        Command::WriteMimic {
            work,
            mode,
            ops,
            data_bytes_per_op,
            index_append_bytes,
            index_checkpoint_every,
            index_end_bytes,
            json_out,
        } => MimicMode::parse(&mode).and_then(|mode| {
            run_write_mimic(&WriteMimicConfig {
                work,
                mode,
                ops,
                data_bytes_per_op,
                index_append_bytes,
                index_checkpoint_every,
                index_end_bytes,
                json_out,
            })
        }),
    };

    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("error: {e}");
            ExitCode::FAILURE
        }
    }
}

fn resolve_seed(seed: u64) -> u64 {
    if seed != 0 {
        return seed;
    }
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0xD160_B17)
}

fn resolve_min_free(spec: &str, target_bytes: u64) -> Result<u64, String> {
    let s = spec.trim();
    if s.eq_ignore_ascii_case("auto") {
        return Ok(default_min_free_for_target(target_bytes));
    }
    parse_size(s)
}

fn cmd_ack_finalize(
    work: PathBuf,
    cell: String,
    target_bytes: String,
    payload_size: usize,
    concurrency: usize,
    seed: u64,
    seal_threshold: String,
    min_free: String,
    enrichment_enabled: bool,
    json_out: bool,
) -> Result<(), String> {
    let target = parse_size(&target_bytes)?;
    let seed = resolve_seed(seed);
    let min_free_bytes = resolve_min_free(&min_free, target)?;
    let seal = parse_size(&seal_threshold)?;
    run_ack_finalize(&AckFinalizeConfig {
        work,
        cell: MeasureCell::parse(&cell)?,
        target_bytes: target,
        payload_size,
        concurrency,
        seed,
        seal_threshold: seal,
        min_free_bytes,
        json_out,
        enrichment_enabled,
    })
    .map(|_| ())
}

fn cmd_ack_finalize_matrix(
    work: PathBuf,
    evidence: PathBuf,
    target_bytes: String,
    payload_size: usize,
    concurrency: usize,
    seed: u64,
    seal_threshold: String,
    min_free: String,
) -> Result<(), String> {
    let target = parse_size(&target_bytes)?;
    let seed = resolve_seed(seed);
    let min_free_bytes = resolve_min_free(&min_free, target)?;
    let seal = parse_size(&seal_threshold)?;
    run_ack_finalize_matrix(
        &work,
        &evidence,
        target,
        payload_size,
        concurrency,
        seed,
        seal,
        min_free_bytes,
    )
}

fn cmd_seal_interference_control(
    work: PathBuf,
    evidence: PathBuf,
    target_bytes: String,
    payload_size: usize,
    concurrency: usize,
    seed: u64,
    min_free: String,
) -> Result<(), String> {
    let target = parse_size(&target_bytes)?;
    let seed = resolve_seed(seed);
    let min_free_bytes = resolve_min_free(&min_free, target)?;
    run_seal_interference_control(
        &work,
        &evidence,
        target,
        payload_size,
        concurrency,
        seed,
        min_free_bytes,
    )
}

fn cmd_seal_fast_lane(
    work: PathBuf,
    evidence: PathBuf,
    target_bytes: String,
    payload_size: usize,
    concurrency: usize,
    seed: u64,
    min_free: String,
) -> Result<(), String> {
    let target = parse_size(&target_bytes)?;
    let seed = resolve_seed(seed);
    let min_free_bytes = resolve_min_free(&min_free, target)?;
    run_seal_fast_lane_measure(
        &work,
        &evidence,
        target,
        payload_size,
        concurrency,
        seed,
        min_free_bytes,
    )
}

fn cmd_enrichment_off_control(
    work: PathBuf,
    evidence: PathBuf,
    target_bytes: String,
    payload_size: usize,
    concurrency: usize,
    seed: u64,
    min_free: String,
) -> Result<(), String> {
    let target = parse_size(&target_bytes)?;
    let seed = resolve_seed(seed);
    let min_free_bytes = resolve_min_free(&min_free, target)?;
    run_enrichment_off_control(
        &work,
        &evidence,
        target,
        payload_size,
        concurrency,
        seed,
        min_free_bytes,
    )
}

fn cmd_zero_scan_auth_seal(
    work: PathBuf,
    evidence: PathBuf,
    target_bytes: String,
    payload_size: usize,
    concurrency: usize,
    seed: u64,
    min_free: String,
) -> Result<(), String> {
    let target = parse_size(&target_bytes)?;
    let seed = resolve_seed(seed);
    let min_free_bytes = resolve_min_free(&min_free, target)?;
    run_zero_scan_auth_seal_measure(
        &work,
        &evidence,
        target,
        payload_size,
        concurrency,
        seed,
        min_free_bytes,
    )
}

fn cmd_peer_pump(
    work: PathBuf,
    engine: String,
    mode: String,
    target_bytes: String,
    payload_size: usize,
    seed: u64,
    min_free: String,
    seal_threshold: String,
    awo_mode: String,
    concurrency: usize,
    diag_io: String,
    segment_growth: String,
    wm_capacity_mib: Option<u64>,
    wm_chunk_mib: Option<u64>,
    diag_skip_index: bool,
    boundary_probe: bool,
    json_out: bool,
) -> Result<(), String> {
    let target = parse_size(&target_bytes)?;
    let seed = resolve_seed(seed);
    let min_free_bytes = resolve_min_free(&min_free, target)?;
    let seal = parse_size(&seal_threshold)?;
    run_peer_pump(&PeerConfig {
        work,
        engine: parse_engine(&engine)?,
        mode: parse_mode(&mode)?,
        target_bytes: target,
        payload_size,
        seed,
        min_free_bytes,
        json_out,
        seal_threshold: seal,
        awo_mode: parse_awo_mode(&awo_mode)?,
        concurrency,
        diag_io: parse_diag_io(&diag_io)?,
        segment_growth: parse_segment_growth(&segment_growth)?,
        wm_capacity_mib,
        wm_chunk_mib,
        diag_skip_index,
        boundary_probe,
    })
}

fn cmd_pump(
    store: PathBuf,
    target_bytes: String,
    payload_size: usize,
    durability: String,
    seal_threshold: String,
    seed: u64,
    key_prefix: String,
    manifest: Option<PathBuf>,
    writer_shards: usize,
    stores: usize,
    min_free: String,
    put_batch_size: usize,
    json_out: bool,
) -> Result<(), String> {
    validate_stores(stores)?;
    ensure_parent(&store).map_err(|e| format!("create parent: {e}"))?;
    let target = parse_size(&target_bytes)?;
    let seal = parse_size(&seal_threshold)?;
    let seed = resolve_seed(seed);
    let durability = parse_durability(&durability)?;
    let min_free_bytes = resolve_min_free(&min_free, target)?;
    // Single-store: manifest sibling of store. Multi-store: aggregate under parent.
    let manifest_path = manifest.unwrap_or_else(|| {
        if stores > 1 {
            store.join(manifest::MANIFEST_FILE)
        } else {
            manifest_path_for_store(&store)
        }
    });
    run_pump(&PumpConfig {
        store,
        target_bytes: target,
        payload_size,
        durability,
        seal_threshold: seal,
        seed,
        key_prefix,
        manifest_path,
        json_out,
        writer_shards,
        store_count: stores,
        min_free_bytes,
        put_batch_size,
    })
    .map(|_| ())
}

fn validate_stores(stores: usize) -> Result<(), String> {
    if stores == 0 {
        return Err("stores must be >= 1".into());
    }
    if stores > MAX_STORES {
        return Err(format!("stores must be <= {MAX_STORES} (got {stores})"));
    }
    Ok(())
}

fn cmd_chaos(
    store: PathBuf,
    hits: u32,
    bytes_per_hit: usize,
    seed: u64,
    protect_head: u64,
    protect_tail: u64,
    brutal: bool,
    json_out: bool,
) -> Result<(), String> {
    let seed = resolve_seed(seed);
    run_chaos(&ChaosConfig {
        store,
        hits,
        bytes_per_hit,
        seed,
        protect_head,
        protect_tail,
        brutal,
        json_out,
    })
    .map(|_| ())
}

fn cmd_monitor(
    store: PathBuf,
    manifest: Option<PathBuf>,
    sample_keys: usize,
    put_samples: usize,
    phase: String,
    inspect_only: bool,
    json_out: bool,
) -> Result<(), String> {
    let r = run_monitor(&MonitorConfig {
        store,
        manifest_path: manifest,
        sample_keys,
        put_samples,
        phase,
        json_out,
        inspect_only,
    })?;
    if r.ok {
        Ok(())
    } else {
        Err(format!("monitor phase `{}` failed", r.phase))
    }
}

fn cmd_run(
    work: PathBuf,
    target_bytes: String,
    payload_size: usize,
    durability: String,
    seal_threshold: String,
    chaos_hits: u32,
    chaos_bytes: usize,
    seed: u64,
    sample_keys: usize,
    brutal: bool,
    writer_shards: usize,
    stores: usize,
    min_free: String,
    json_out: bool,
) -> Result<(), String> {
    validate_stores(stores)?;
    std::fs::create_dir_all(&work).map_err(|e| format!("create work dir: {e}"))?;
    let target = parse_size(&target_bytes)?;
    let seal = parse_size(&seal_threshold)?;
    let seed = resolve_seed(seed);
    let durability = parse_durability(&durability)?;
    let min_free_bytes = resolve_min_free(&min_free, target)?;

    // Layout: single-store keeps `work/store` for backward compatibility.
    // Multi-store (Axis C): parent is `work`; children at `work/store-00` …
    let pump_root = if stores > 1 {
        work.clone()
    } else {
        work.join("store")
    };
    let manifest_path = work.join(manifest::MANIFEST_FILE);
    let store_paths: Vec<PathBuf> = (0..stores)
        .map(|i| store_path_for(&pump_root, i, stores))
        .collect();

    if !json_out {
        println!(
            "=== testrig run ===\nwork={}\nstores={stores} roots={}\ntarget={}\npayload={} durability={:?} writer_shards={writer_shards} seed={seed}",
            work.display(),
            if stores > 1 {
                format!("{}…{}", store_paths[0].display(), store_paths[stores - 1].display())
            } else {
                store_paths[0].display().to_string()
            },
            format_bytes(target),
            payload_size,
            durability
        );
        println!("\n--- prong 1: pump ---");
    }

    let pump_manifest = run_pump(&PumpConfig {
        store: pump_root.clone(),
        target_bytes: target,
        payload_size,
        durability,
        seal_threshold: seal,
        seed,
        key_prefix: "load/".into(),
        manifest_path: manifest_path.clone(),
        json_out: false, // orchestrator owns final JSON
        writer_shards,
        store_count: stores,
        min_free_bytes,
        put_batch_size: 0,
    })?;

    // Per-store monitor + chaos (each root is independent).
    let mut baseline_reports: Vec<Value> = Vec::with_capacity(stores);
    let mut post_reports: Vec<Value> = Vec::with_capacity(stores);
    let mut chaos_hits_total = 0u32;
    let mut chaos_reports: Vec<Value> = Vec::with_capacity(stores);
    let mut all_reasons: Vec<String> = Vec::new();
    let mut pass = true;

    for i in 0..stores {
        let store = &store_paths[i];
        let per_manifest = if stores > 1 {
            per_store_manifest_path(&work, i, stores)
        } else {
            manifest_path.clone()
        };

        if !json_out {
            if stores > 1 {
                println!("\n--- prong 3a: baseline monitor [store-{i:02}] ---");
            } else {
                println!("\n--- prong 3a: baseline monitor ---");
            }
        }
        let baseline = run_monitor(&MonitorConfig {
            store: store.clone(),
            manifest_path: Some(per_manifest.clone()),
            sample_keys,
            put_samples: 16,
            phase: "baseline".into(),
            json_out: false,
            inspect_only: false,
        })?;
        baseline_reports.push(baseline.report.clone());

        if !json_out {
            if stores > 1 {
                println!("\n--- prong 2: chaos [store-{i:02}] ---");
            } else {
                println!("\n--- prong 2: chaos ---");
            }
        }
        // Store must be closed — monitors already dropped their handles.
        let chaos = run_chaos(&ChaosConfig {
            store: store.clone(),
            hits: chaos_hits,
            bytes_per_hit: chaos_bytes,
            seed: seed ^ 0xC4A0_5 ^ (i as u64).wrapping_mul(0xA5A5_A5A5),
            protect_head: 4096,
            protect_tail: 64,
            brutal,
            json_out: false,
        })?;
        chaos_hits_total = chaos_hits_total.saturating_add(chaos.hits_applied);
        chaos_reports.push(json!({
            "store": store.display().to_string(),
            "hits_applied": chaos.hits_applied,
            "hits_requested": chaos.hits_requested,
            "candidate_files": chaos.candidate_files,
        }));

        if !json_out {
            if stores > 1 {
                println!("\n--- prong 3b: post-chaos monitor [store-{i:02}] ---");
            } else {
                println!("\n--- prong 3b: post-chaos monitor ---");
            }
        }
        let post = run_monitor(&MonitorConfig {
            store: store.clone(),
            manifest_path: Some(per_manifest),
            sample_keys,
            // After chaos, avoid writer puts that might seal over damage mid-bench.
            put_samples: 0,
            phase: "post-chaos".into(),
            json_out: false,
            inspect_only: true,
        })?;
        post_reports.push(post.report.clone());

        let (store_pass, store_reasons) = evaluate_run(&baseline, chaos.hits_applied, &post);
        if !store_pass {
            pass = false;
        }
        for r in store_reasons {
            if stores > 1 {
                all_reasons.push(format!("store-{i:02}: {r}"));
            } else {
                all_reasons.push(r);
            }
        }
    }

    let summary = json!({
        "prong": "run",
        "ok": pass,
        "work": work.display().to_string(),
        "store": store_paths[0].display().to_string(),
        "store_count": stores,
        "store_paths": store_paths.iter().map(|p| p.display().to_string()).collect::<Vec<_>>(),
        "target_bytes": target,
        "bytes_on_disk": pump_manifest.bytes_on_disk,
        "keys_written": pump_manifest.keys_written,
        "pump_ops_per_sec": pump_manifest.pump_ops_per_sec,
        "pump_mb_per_sec": pump_manifest.pump_mb_per_sec,
        "pump_elapsed_ms": pump_manifest.pump_elapsed_ms,
        // Multi-core / multi-process disclosure (doc/reference/operations/BENCHMARK_DISCLOSURE.md, DEF-096).
        "concurrency": pump_manifest.concurrency,
        "writer_shards": pump_manifest.writer_shards,
        "writer_model": pump_manifest.writer_model,
        "peak_rss_bytes": pump_manifest.peak_rss_bytes,
        "peak_cpu_pct": pump_manifest.peak_cpu_pct,
        "chaos_hits": chaos_hits_total,
        "chaos_by_store": chaos_reports,
        "baseline": if stores == 1 { baseline_reports[0].clone() } else { json!(baseline_reports) },
        "post_chaos": if stores == 1 { post_reports[0].clone() } else { json!(post_reports) },
        "reasons": all_reasons,
        "ladder_hint": "If ok at 1G, re-run with --target-bytes 10G (then larger). Axis B: --writer-shards N. Axis C: --stores N (multi-process).",
        "disclosure": "Diagnostic only — not a published SLO (doc/reference/operations/BENCHMARK_DISCLOSURE.md).",
    });

    let summary_path = work.join("testrig-summary.v1.json");
    std::fs::write(&summary_path, serde_json::to_vec_pretty(&summary).unwrap())
        .map_err(|e| format!("write summary: {e}"))?;

    if json_out {
        println!("{}", serde_json::to_string_pretty(&summary).unwrap());
    } else {
        println!("\n=== result: {} ===", if pass { "PASS" } else { "FAIL" });
        for r in &all_reasons {
            println!("  - {r}");
        }
        println!("summary: {}", summary_path.display());
        println!(
            "ladder: pass here, then retry with --target-bytes 10G (then more); Axis C: --stores N"
        );
    }

    if pass {
        Ok(())
    } else {
        Err("testrig run failed (see reasons above)".into())
    }
}
