//! Prong 1 — autogenerated data pump targeting a storage footprint.
//!
//! Single-store path pumps one `Store`. With `--stores N` (N>1) the harness
//! spawns N child processes, each owning an independent store root under the
//! parent directory (`store-00` …) — DEF-096 **Axis C** multi-process capacity.

use crate::manifest::{
    per_store_manifest_path, store_path_for, write_manifest, WorkloadManifest, MAX_STORES,
};
use crate::size::{dir_size_bytes, ensure_free_space, format_bytes};
use residiuum_store::{DurabilityMode, Store, StorePaths, MAX_WRITER_SHARDS};
use serde_json::{json, Value};
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::Instant;

#[derive(Debug, Clone)]
pub struct PumpConfig {
    /// Store root (single-store) or parent directory of `store-00`… when `store_count > 1`.
    pub store: PathBuf,
    pub target_bytes: u64,
    pub payload_size: usize,
    pub durability: DurabilityMode,
    pub seal_threshold: u64,
    pub seed: u64,
    pub key_prefix: String,
    pub manifest_path: PathBuf,
    pub json_out: bool,
    /// Number of writer shards (DEF-096 Axis B). `1` = legacy single active segment.
    /// Values `> 1` create with `Store::create_with_shards` and pump via `put_many`.
    pub writer_shards: usize,
    /// Independent store roots (DEF-096 Axis C). `1` = single process; `N>1` spawns
    /// N child `pump` processes under `store/store-00` … `store/store-(N-1)`.
    pub store_count: usize,
    /// Minimum free space required on the store volume before pumping.
    /// `0` disables the floor. Default callers use [`default_min_free_for_target`].
    pub min_free_bytes: u64,
    /// Override put batch size (`0` = auto from shard count). Use `1` to measure
    /// general single-put load (one OS tail write per key for Buffered).
    pub put_batch_size: usize,
}

/// Peak process resource samples collected during the pump (diagnostic).
#[derive(Debug, Clone, Default)]
struct ProcessSamples {
    /// Peak RSS in bytes (from `ps` RSS column, KiB → bytes).
    peak_rss_bytes: Option<u64>,
    /// Peak process CPU% as reported by `ps` (on macOS: 100% ≈ one core).
    peak_cpu_pct: Option<f64>,
    /// Last observed CPU%.
    last_cpu_pct: Option<f64>,
    /// Number of successful `ps` samples.
    sample_count: u64,
}

pub fn run_pump(cfg: &PumpConfig) -> Result<WorkloadManifest, String> {
    validate_pump_cfg(cfg)?;
    // Fail closed when the volume is near full — contaminated rates are worse than no run.
    let free = ensure_free_space(&cfg.store, cfg.min_free_bytes)?;
    if !cfg.json_out && cfg.min_free_bytes > 0 {
        eprintln!(
            "pump free-space ok: free={} min-free={} path={}",
            format_bytes(free),
            format_bytes(cfg.min_free_bytes),
            cfg.store.display()
        );
    }
    if cfg.store_count > 1 {
        run_pump_multi_process(cfg)
    } else {
        run_pump_single(cfg)
    }
}

fn validate_pump_cfg(cfg: &PumpConfig) -> Result<(), String> {
    if cfg.target_bytes == 0 {
        return Err("target-bytes must be > 0".into());
    }
    if cfg.payload_size == 0 {
        return Err("payload-size must be > 0".into());
    }
    if cfg.writer_shards == 0 {
        return Err("writer-shards must be >= 1".into());
    }
    if cfg.writer_shards > MAX_WRITER_SHARDS {
        return Err(format!(
            "writer-shards must be <= {MAX_WRITER_SHARDS} (got {})",
            cfg.writer_shards
        ));
    }
    if cfg.store_count == 0 {
        return Err("stores must be >= 1".into());
    }
    if cfg.store_count > MAX_STORES {
        return Err(format!(
            "stores must be <= {MAX_STORES} (got {})",
            cfg.store_count
        ));
    }
    Ok(())
}

/// Axis C: N independent store roots, each pumped by a child process.
///
/// Parent dir is `cfg.store`; children live at `store-00` … `store-(N-1)`.
/// Aggregate wall-clock ops/s = sum(keys) / parent wall time (honest multi-process capacity).
fn run_pump_multi_process(cfg: &PumpConfig) -> Result<WorkloadManifest, String> {
    let n = cfg.store_count;
    fs::create_dir_all(&cfg.store).map_err(|e| format!("create multi-store parent: {e}"))?;

    // Split target across stores so total footprint ≈ campaign target (fair ladder).
    let per_target = (cfg.target_bytes + n as u64 - 1) / n as u64;
    let per_target = per_target.max(1);

    let exe = std::env::current_exe().map_err(|e| format!("current_exe: {e}"))?;
    if !cfg.json_out {
        eprintln!(
            "pump multi-store: stores={n} parent={} per_store_target={} writer_shards={} (Axis C multi-process)",
            cfg.store.display(),
            format_bytes(per_target),
            cfg.writer_shards
        );
    }

    let t0 = Instant::now();
    let mut children = Vec::with_capacity(n);
    let mut store_paths = Vec::with_capacity(n);

    for i in 0..n {
        let store_path = store_path_for(&cfg.store, i, n);
        let manifest_path = per_store_manifest_path(&cfg.store, i, n);
        ensure_parent(&store_path).map_err(|e| format!("create store parent: {e}"))?;
        store_paths.push(store_path.display().to_string());

        // Distinct seed per store so payload patterns differ; keys remain independent.
        let child_seed = cfg
            .seed
            .wrapping_add((i as u64).wrapping_mul(0x9E37_79B9_7F4A_7C15));

        let mut cmd = Command::new(&exe);
        cmd.arg("pump")
            .arg("--store")
            .arg(&store_path)
            .arg("--target-bytes")
            .arg(per_target.to_string())
            .arg("--payload-size")
            .arg(cfg.payload_size.to_string())
            .arg("--durability")
            .arg(durability_label(cfg.durability))
            .arg("--seal-threshold")
            .arg(cfg.seal_threshold.to_string())
            .arg("--seed")
            .arg(child_seed.to_string())
            .arg("--key-prefix")
            .arg(&cfg.key_prefix)
            .arg("--manifest")
            .arg(&manifest_path)
            .arg("--writer-shards")
            .arg(cfg.writer_shards.to_string())
            // Children are always single-store (store_count defaults to 1).
            // Parent already enforced the floor for total footprint; children skip re-check.
            .arg("--min-free")
            .arg("0")
            .arg("--json-out")
            .stdout(Stdio::piped())
            .stderr(Stdio::inherit());

        let child = cmd
            .spawn()
            .map_err(|e| format!("spawn pump child {i} ({}): {e}", store_path.display()))?;
        children.push((i, store_path, manifest_path, child));
    }

    let mut child_reports: Vec<(usize, Value)> = Vec::with_capacity(n);
    let mut failed = false;
    let mut fail_msg = String::new();

    for (i, store_path, manifest_path, child) in children {
        let output = child
            .wait_with_output()
            .map_err(|e| format!("wait pump child {i}: {e}"))?;
        if !output.status.success() {
            failed = true;
            let stderr_tail = String::from_utf8_lossy(&output.stderr);
            fail_msg = format!(
                "pump child {i} ({}) exited {}: {}",
                store_path.display(),
                output.status,
                stderr_tail.chars().take(400).collect::<String>()
            );
            // Continue draining siblings so we don't leave zombies; still fail.
            continue;
        }
        let stdout = String::from_utf8_lossy(&output.stdout);
        let report: Value = serde_json::from_str(stdout.trim()).map_err(|e| {
            format!(
                "parse pump child {i} JSON from {}: {e}; stdout_head={}",
                store_path.display(),
                stdout.chars().take(200).collect::<String>()
            )
        })?;
        if report.get("ok").and_then(|v| v.as_bool()) != Some(true) {
            failed = true;
            fail_msg = format!(
                "pump child {i} ({}) reported ok=false",
                store_path.display()
            );
            continue;
        }
        // Prefer re-reading the child manifest for stable aggregate fields.
        let _ = manifest_path;
        child_reports.push((i, report));
    }

    if failed {
        return Err(fail_msg);
    }
    child_reports.sort_by_key(|(i, _)| *i);

    let elapsed = t0.elapsed();
    let secs = elapsed.as_secs_f64().max(1e-9);

    let mut keys_written = 0u64;
    let mut bytes_on_disk = 0u64;
    let mut sum_rss: Option<u64> = None;
    let mut sum_cpu: Option<f64> = None;
    let mut actual_shards = cfg.writer_shards;

    for (_, r) in &child_reports {
        keys_written = keys_written.saturating_add(json_u64(r, "keys_written"));
        bytes_on_disk = bytes_on_disk.saturating_add(json_u64(r, "bytes_on_disk"));
        if let Some(rss) = r.get("peak_rss_bytes").and_then(|v| v.as_u64()) {
            sum_rss = Some(sum_rss.unwrap_or(0).saturating_add(rss));
        }
        if let Some(cpu) = r.get("peak_cpu_pct").and_then(|v| v.as_f64()) {
            sum_cpu = Some(sum_cpu.unwrap_or(0.0) + cpu);
        }
        if let Some(ws) = r.get("writer_shards").and_then(|v| v.as_u64()) {
            actual_shards = ws as usize;
        }
    }

    // Wall-clock aggregate: sum of keys / parent wall time (parallel capacity).
    let ops_per_sec = keys_written as f64 / secs;
    let mb_per_sec = (bytes_on_disk as f64 / (1024.0 * 1024.0)) / secs;
    let concurrency = n.saturating_mul(actual_shards.max(1));
    let writer_model = if actual_shards > 1 {
        "multi_process_stores_sharded".to_string()
    } else {
        "multi_process_stores".to_string()
    };

    let manifest = WorkloadManifest {
        format_version: 1,
        store_path: cfg.store.display().to_string(),
        target_bytes: cfg.target_bytes,
        payload_size: cfg.payload_size,
        durability: durability_label(cfg.durability).into(),
        keys_written,
        first_key: format!("{}{:020}", cfg.key_prefix, 0),
        last_key: format!("{}{:020}", cfg.key_prefix, keys_written.saturating_sub(1)),
        key_prefix: cfg.key_prefix.clone(),
        bytes_on_disk,
        pump_elapsed_ms: elapsed.as_millis() as u64,
        pump_ops_per_sec: ops_per_sec,
        pump_mb_per_sec: mb_per_sec,
        seed: cfg.seed,
        writer_shards: actual_shards,
        concurrency,
        writer_model: writer_model.clone(),
        store_count: n,
        store_paths: store_paths.clone(),
        peak_rss_bytes: sum_rss,
        peak_cpu_pct: sum_cpu,
    };

    write_manifest(&cfg.manifest_path, &manifest)
        .map_err(|e| format!("write aggregate manifest: {e}"))?;

    let report = json!({
        "prong": "pump",
        "ok": bytes_on_disk >= cfg.target_bytes,
        "keys_written": keys_written,
        "bytes_on_disk": bytes_on_disk,
        "target_bytes": cfg.target_bytes,
        "payload_size": cfg.payload_size,
        "durability": durability_label(cfg.durability),
        "elapsed_ms": manifest.pump_elapsed_ms,
        "ops_per_sec": ops_per_sec,
        "mb_per_sec": mb_per_sec,
        "concurrency": concurrency,
        "writer_shards": actual_shards,
        "writer_model": writer_model,
        "store_count": n,
        "store_paths": store_paths,
        "per_store_target_bytes": per_target,
        "peak_rss_bytes": sum_rss,
        "peak_cpu_pct": sum_cpu,
        "child_reports": child_reports.iter().map(|(_, r)| r).collect::<Vec<_>>(),
        "manifest": cfg.manifest_path.display().to_string(),
        "store": cfg.store.display().to_string(),
        "pump_mode": "multi_process",
        "disclosure": "Diagnostic only — not a published SLO (doc/reference/operations/BENCHMARK_DISCLOSURE.md). Axis C multi-store harness.",
    });

    if cfg.json_out {
        println!("{}", serde_json::to_string_pretty(&report).unwrap());
    } else {
        println!(
            "pump done (multi-process): stores={n} keys={keys_written} shards/store={actual_shards} model={writer_model} disk={} (target {}) in {:.2}s — {:.1} ops/s wall, {:.2} MB/s",
            format_bytes(bytes_on_disk),
            format_bytes(cfg.target_bytes),
            secs,
            ops_per_sec,
            mb_per_sec
        );
        if let Some(rss) = sum_rss {
            println!(
                "  peak_rss_sum={}  peak_cpu%_sum={}  concurrency={concurrency}  (child ps samples; macOS 100%≈1 core)",
                format_bytes(rss),
                sum_cpu
                    .map(|c| format!("{c:.0}"))
                    .unwrap_or_else(|| "n/a".into())
            );
        }
        println!("manifest: {}", cfg.manifest_path.display());
    }

    if bytes_on_disk < cfg.target_bytes {
        return Err(format!(
            "multi-store pump under target: {} < {}",
            format_bytes(bytes_on_disk),
            format_bytes(cfg.target_bytes)
        ));
    }
    Ok(manifest)
}

fn json_u64(v: &Value, key: &str) -> u64 {
    v.get(key)
        .and_then(|x| x.as_u64().or_else(|| x.as_f64().map(|f| f as u64)))
        .unwrap_or(0)
}

/// Single-store in-process pump (Axis A/B path).
fn run_pump_single(cfg: &PumpConfig) -> Result<WorkloadManifest, String> {
    let mut store = open_or_create_store(&cfg.store, cfg.writer_shards)?;
    store.set_seal_threshold(cfg.seal_threshold);
    let actual_shards = store.writer_shards();
    let writer_model = store.writer_model().to_string();

    // Deterministic-looking payload body (not crypto). Pattern helps spot garbage later.
    let mut payload = vec![0u8; cfg.payload_size];
    fill_payload(&mut payload, cfg.seed);

    let t0 = Instant::now();
    let mut keys_written = 0u64;
    let mut last_report = Instant::now();
    let mut samples = ProcessSamples::default();

    // Progress uses sum of WriteReceipt.encoded_frame_len (no mid-run dir walks).
    // Final acceptance still measures real on-disk size once after seal.
    let batch_size = if cfg.put_batch_size == 0 {
        put_batch_size(actual_shards)
    } else {
        cfg.put_batch_size.max(1)
    };
    let mut pending_keys: Vec<String> = Vec::with_capacity(batch_size);
    let mut encoded_bytes: u64 = 0;
    let mut reached_target = false;

    while !reached_target {
        let key = format!("{}{:020}", cfg.key_prefix, keys_written);
        pending_keys.push(key);
        keys_written += 1;

        if pending_keys.len() >= batch_size {
            encoded_bytes = encoded_bytes.saturating_add(flush_puts(
                &mut store,
                &pending_keys,
                &payload,
                cfg.durability,
            )?);
            pending_keys.clear();
            if encoded_bytes >= cfg.target_bytes {
                reached_target = true;
            }
        }

        // Resource sample on ~2s cadence (not tied to expensive dir walks).
        if last_report.elapsed().as_secs() >= 2 || keys_written == 1 {
            sample_process(&mut samples);
            if !cfg.json_out {
                let elapsed = t0.elapsed().as_secs_f64().max(1e-9);
                let rss_note = samples
                    .peak_rss_bytes
                    .map(|b| format!(" peak_rss={}", format_bytes(b)))
                    .unwrap_or_default();
                let cpu_note = samples
                    .last_cpu_pct
                    .map(|c| format!(" cpu={c:.0}%"))
                    .unwrap_or_default();
                eprintln!(
                    "pump: keys={keys_written} shards={actual_shards} encoded≈{} / {} ({:.1}%) {:.1} ops/s {:.2} MB/s{cpu_note}{rss_note}",
                    format_bytes(encoded_bytes),
                    format_bytes(cfg.target_bytes),
                    100.0 * encoded_bytes as f64 / cfg.target_bytes.max(1) as f64,
                    keys_written as f64 / elapsed,
                    (encoded_bytes as f64 / (1024.0 * 1024.0)) / elapsed
                );
            }
            last_report = Instant::now();
        }

        // Safety: if payload is tiny and metadata dominates oddly, still stop.
        if keys_written >= 50_000_000 {
            return Err(
                "pump abort: 50M keys without reaching target (raise payload-size?)".into(),
            );
        }
    }

    // Flush any trailing keys left after the last full batch.
    if !pending_keys.is_empty() {
        encoded_bytes = encoded_bytes.saturating_add(flush_puts(
            &mut store,
            &pending_keys,
            &payload,
            cfg.durability,
        )?);
        pending_keys.clear();
    }
    // `encoded_bytes` is the mid-run progress meter; final report uses dir size.
    let _encoded_progress = encoded_bytes;

    // Final resource sample before seal (seal can be heavy).
    sample_process(&mut samples);

    // Seal active so chaos has sealed segment files to punch.
    let _ = store.seal_active();
    drop(store);

    let elapsed = t0.elapsed();
    let bytes_on_disk = dir_size_bytes(&cfg.store).map_err(|e| format!("dir size: {e}"))?;
    let secs = elapsed.as_secs_f64().max(1e-9);
    let ops_per_sec = keys_written as f64 / secs;
    let mb_per_sec = (bytes_on_disk as f64 / (1024.0 * 1024.0)) / secs;

    // Honest concurrency: number of active writer shards / parallel append paths.
    // put_many fans out across shards; with shards==1 this remains a single path.
    let concurrency = actual_shards;

    let manifest = WorkloadManifest {
        format_version: 1,
        store_path: cfg.store.display().to_string(),
        target_bytes: cfg.target_bytes,
        payload_size: cfg.payload_size,
        durability: durability_label(cfg.durability).into(),
        keys_written,
        first_key: format!("{}{:020}", cfg.key_prefix, 0),
        last_key: format!("{}{:020}", cfg.key_prefix, keys_written.saturating_sub(1)),
        key_prefix: cfg.key_prefix.clone(),
        bytes_on_disk,
        pump_elapsed_ms: elapsed.as_millis() as u64,
        pump_ops_per_sec: ops_per_sec,
        pump_mb_per_sec: mb_per_sec,
        seed: cfg.seed,
        writer_shards: actual_shards,
        concurrency,
        writer_model: writer_model.clone(),
        store_count: 1,
        store_paths: vec![cfg.store.display().to_string()],
        peak_rss_bytes: samples.peak_rss_bytes,
        peak_cpu_pct: samples.peak_cpu_pct,
    };

    write_manifest(&cfg.manifest_path, &manifest).map_err(|e| format!("write manifest: {e}"))?;

    let report = json!({
        "prong": "pump",
        "ok": bytes_on_disk >= cfg.target_bytes,
        "keys_written": keys_written,
        "bytes_on_disk": bytes_on_disk,
        "target_bytes": cfg.target_bytes,
        "payload_size": cfg.payload_size,
        "durability": durability_label(cfg.durability),
        "elapsed_ms": manifest.pump_elapsed_ms,
        "ops_per_sec": ops_per_sec,
        "mb_per_sec": mb_per_sec,
        // Honest concurrency disclosure (doc/reference/operations/BENCHMARK_DISCLOSURE.md, DEF-096).
        "concurrency": concurrency,
        "writer_shards": actual_shards,
        "writer_model": writer_model,
        "store_count": 1,
        "put_batch_size": batch_size,
        "peak_rss_bytes": samples.peak_rss_bytes,
        "peak_cpu_pct": samples.peak_cpu_pct,
        "process_sample_count": samples.sample_count,
        "manifest": cfg.manifest_path.display().to_string(),
        "store": cfg.store.display().to_string(),
        "pump_mode": "single_process",
        "disclosure": "Diagnostic only — not a published SLO (doc/reference/operations/BENCHMARK_DISCLOSURE.md).",
    });

    if cfg.json_out {
        println!("{}", serde_json::to_string_pretty(&report).unwrap());
    } else {
        println!(
            "pump done: keys={keys_written} shards={actual_shards} model={writer_model} disk={} (target {}) in {:.2}s — {:.1} ops/s, {:.2} MB/s",
            format_bytes(bytes_on_disk),
            format_bytes(cfg.target_bytes),
            secs,
            ops_per_sec,
            mb_per_sec
        );
        if let Some(rss) = samples.peak_rss_bytes {
            println!(
                "  peak_rss={}  peak_cpu%={}  (ps samples; macOS 100%≈1 core)",
                format_bytes(rss),
                samples
                    .peak_cpu_pct
                    .map(|c| format!("{c:.0}"))
                    .unwrap_or_else(|| "n/a".into())
            );
        }
        println!("manifest: {}", cfg.manifest_path.display());
    }

    if bytes_on_disk < cfg.target_bytes {
        return Err(format!(
            "pump under target: {} < {}",
            format_bytes(bytes_on_disk),
            format_bytes(cfg.target_bytes)
        ));
    }
    Ok(manifest)
}

/// Open existing store, or create with the requested writer shard count.
///
/// If the store already exists, its on-disk shard count is authoritative. A
/// mismatched `--writer-shards` is an error so campaigns stay honest.
fn open_or_create_store(path: &Path, writer_shards: usize) -> Result<Store, String> {
    let paths = StorePaths::new(path);
    if paths.looks_like_store() {
        let store = Store::open(path).map_err(|e| format!("open store: {e}"))?;
        let actual = store.writer_shards();
        if actual != writer_shards {
            return Err(format!(
                "store at {} has writer_shards={actual}, but --writer-shards={writer_shards} was requested \
                 (shard count is fixed at create; recreate the store or match the flag)",
                path.display()
            ));
        }
        return Ok(store);
    }
    // Not a store yet: create with the requested shard layout (DEF-096 Axis B).
    Store::create_with_shards(path, writer_shards)
        .map_err(|e| format!("create store with {writer_shards} writer shards: {e}"))
}

/// Flush keys via `put_many`. Returns sum of `encoded_frame_len` for progress.
fn flush_puts(
    store: &mut Store,
    keys: &[String],
    payload: &[u8],
    durability: DurabilityMode,
) -> Result<u64, String> {
    if keys.is_empty() {
        return Ok(0);
    }
    // Always use put_many so single-shard batches get one segment tail write
    // (store amortizes seek+write_all). Len==1 still goes through put_many.
    let items: Vec<(&str, &[u8])> = keys.iter().map(|k| (k.as_str(), payload)).collect();
    let receipts = store
        .put_many(&items, durability)
        .map_err(|e| format!("put_many ({} keys): {e}", keys.len()))?;
    Ok(receipts.iter().map(|r| r.encoded_frame_len).sum())
}

fn put_batch_size(writer_shards: usize) -> usize {
    // Single-shard: batch so store issues one file tail write per flush instead
    // of one seek+write_all per key (was the primary SSD under-utilization cause).
    // Multi-shard: larger batches keep shard threads fed after partition.
    if writer_shards <= 1 {
        128
    } else {
        (writer_shards * 64).clamp(128, 1024)
    }
}

fn sample_process(samples: &mut ProcessSamples) {
    let Some((cpu, rss_kib)) = read_self_ps() else {
        return;
    };
    samples.sample_count += 1;
    samples.last_cpu_pct = Some(cpu);
    samples.peak_cpu_pct = Some(samples.peak_cpu_pct.map(|p| p.max(cpu)).unwrap_or(cpu));
    let rss_bytes = rss_kib.saturating_mul(1024);
    samples.peak_rss_bytes = Some(
        samples
            .peak_rss_bytes
            .map(|p| p.max(rss_bytes))
            .unwrap_or(rss_bytes),
    );
}

/// Best-effort self sample via `ps` (macOS / Linux). Returns (cpu_pct, rss_kib).
fn read_self_ps() -> Option<(f64, u64)> {
    let pid = std::process::id().to_string();
    let output = Command::new("ps")
        .args(["-o", "%cpu=,rss=", "-p", &pid])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let text = String::from_utf8_lossy(&output.stdout);
    let parts: Vec<&str> = text.split_whitespace().collect();
    if parts.len() < 2 {
        return None;
    }
    let cpu: f64 = parts[0].parse().ok()?;
    let rss_kib: u64 = parts[1].parse().ok()?;
    Some((cpu, rss_kib))
}

fn fill_payload(buf: &mut [u8], seed: u64) {
    // Simple LCG fill — fast and reproducible for a given seed.
    let mut state = seed ^ 0xD1_160_B17_u64;
    for (i, b) in buf.iter_mut().enumerate() {
        state = state.wrapping_mul(6364136223846793005).wrapping_add(1);
        *b = ((state >> 33) as u8).wrapping_add((i & 0xff) as u8);
    }
    // Magic prefix so corrupted regions are obvious in hex dumps.
    let magic = b"RESIDIUUM-TESTRIG-PAYLOAD-v1\n";
    let n = magic.len().min(buf.len());
    buf[..n].copy_from_slice(&magic[..n]);
}

pub fn durability_label(d: DurabilityMode) -> &'static str {
    match d {
        DurabilityMode::Memory => "memory",
        DurabilityMode::Buffered => "buffered",
        DurabilityMode::Durable => "durable",
    }
}

pub fn parse_durability(s: &str) -> Result<DurabilityMode, String> {
    match s.to_ascii_lowercase().as_str() {
        "memory" | "mem" => Ok(DurabilityMode::Memory),
        "buffered" | "buffer" | "buf" => Ok(DurabilityMode::Buffered),
        "durable" | "sync" | "fsync" => Ok(DurabilityMode::Durable),
        other => Err(format!(
            "unknown durability `{other}` (memory|buffered|durable)"
        )),
    }
}

/// Ensure parent dirs exist for store path.
pub fn ensure_parent(store: &Path) -> io::Result<()> {
    if let Some(p) = store.parent() {
        fs::create_dir_all(p)?;
    }
    Ok(())
}
